<?php

require_once __DIR__.'/../Fixtures/ProjectTemplateDebugger.php';

/**
 * Test class for Symfony_Component_Templating_Loader_Loader.
 * Generated by PHPUnit on 2012-02-25 at 20:17:25.
 */
class Symfony_Component_Templating_Loader_LoaderTest extends PHPUnit_Framework_TestCase
{

	public function testGetSetDebugger()
    {
        $loader = new Symfony_Component_Templating_Loader_ProjectTemplateLoader4(new Symfony_Component_Templating_TemplateNameParser());
        $loader->setDebugger($debugger = new ProjectTemplateDebugger());
        $this->assertTrue($loader->getDebugger() === $debugger, '->setDebugger() sets the debugger instance');
    }
}

class Symfony_Component_Templating_Loader_ProjectTemplateLoader4 extends Symfony_Component_Templating_Loader_Loader
{
    public function load(Symfony_Component_Templating_TemplateReferenceInterface $template)
    {
    }

    public function getDebugger()
    {
        return $this->debugger;
    }

    public function isFresh(Symfony_Component_Templating_TemplateReferenceInterface $template, $time)
    {
        return false;
    }
}

?>
