<?php

/**
 * Test class for Symfony_Component_Templating_Helper_CoreAssetsHelper.
 * Generated by PHPUnit on 2012-02-25 at 19:00:34.
 */
class Symfony_Component_Templating_Helper_CoreAssetsHelperTest extends PHPUnit_Framework_TestCase
{

	/**
	 * @var Symfony_Component_Templating_Helper_CoreAssetsHelper
	 */
	protected $package;

    public function setUp()
    {
        $this->package = $this->getMock('Symfony_Component_Templating_Asset_PackageInterface');
    }

    protected function tearDown()
    {
        $this->package = null;
    }

    public function testAddGetPackage()
    {
        $helper = new Symfony_Component_Templating_Helper_CoreAssetsHelper($this->package);

        $helper->addPackage('foo', $this->package);

        $this->assertSame($this->package, $helper->getPackage('foo'));
    }

    public function testGetNonexistingPackage()
    {
        $helper = new Symfony_Component_Templating_Helper_CoreAssetsHelper($this->package);

        $this->setExpectedException('InvalidArgumentException');

        $helper->getPackage('foo');
    }

    public function testGetHelperName()
    {
        $helper = new Symfony_Component_Templating_Helper_CoreAssetsHelper($this->package);

        $this->assertEquals('assets', $helper->getName());
    }

}

?>
