<?php

/**
 * Test class for Symfony_Component_Templating_Helper_Helper.
 * Generated by PHPUnit on 2012-02-25 at 19:26:18.
 */
class Symfony_Component_Templating_Helper_HelperTest extends PHPUnit_Framework_TestCase
{

	public function testGetSetCharset()
    {
        $helper = new ProjectTemplateHelper();
        $helper->setCharset('ISO-8859-1');
        $this->assertTrue('ISO-8859-1' === $helper->getCharset(), '->setCharset() sets the charset set related to this helper');
    }
}

class ProjectTemplateHelper extends Symfony_Component_Templating_Helper_Helper
{
    public function getName()
    {
        return 'foo';
    }
}

?>
