<?php

/**
 * Test class for Symfony_Component_Templating_TemplateNameParser.
 * Generated by PHPUnit on 2012-02-25 at 18:21:19.
 */
class Symfony_Component_Templating_TemplateNameParserTest extends PHPUnit_Framework_TestCase
{

	/**
	 * @var Symfony_Component_Templating_TemplateNameParser
	 */
	protected $parser;

    protected function setUp()
    {
        $this->parser = new Symfony_Component_Templating_TemplateNameParser();
    }

    protected function tearDown()
    {
        $this->parser = null;
    }

    /**
     * @dataProvider getLogicalNameToTemplateProvider
     */
    public function testParse($name, $ref)
    {
        $template = $this->parser->parse($name);

        $this->assertEquals($template->getLogicalName(), $ref->getLogicalName());
        $this->assertEquals($template->getLogicalName(), $name);
    }

    public function getLogicalNameToTemplateProvider()
    {
        return array(
            array('/path/to/section/name.engine', new Symfony_Component_Templating_TemplateReference('/path/to/section/name.engine', 'engine')),
            array('name.engine', new Symfony_Component_Templating_TemplateReference('name.engine', 'engine')),
            array('name', new Symfony_Component_Templating_TemplateReference('name')),
        );
    }

}

?>
