<?php

/**
 * Test class for Symfony_Component_Templating_Storage_StringStorage.
 * Generated by PHPUnit on 2012-02-25 at 20:28:00.
 */
class Symfony_Component_Templating_Storage_StringStorageTest extends PHPUnit_Framework_TestCase
{

	public function testGetContent()
    {
        $storage = new Symfony_Component_Templating_Storage_StringStorage('foo');
        $this->assertInstanceOf('Symfony_Component_Templating_Storage_Storage', $storage, 'StringStorage is an instance of Storage');
        $storage = new Symfony_Component_Templating_Storage_StringStorage('foo');
        $this->assertEquals('foo', $storage->getContent(), '->getContent() returns the content of the template');
    }

}

?>
