<?php

/**
 * Test class for Symfony_Component_Templating_Storage_Storage.
 * Generated by PHPUnit on 2012-02-25 at 20:26:11.
 */
class Symfony_Component_Templating_Storage_StorageTest extends PHPUnit_Framework_TestCase
{

	public function testMagicToString()
    {
        $storage = new Symfony_Component_Templating_Storage_TestStorage('foo');
        $this->assertEquals('foo', (string) $storage, '__toString() returns the template name');
    }
}

class Symfony_Component_Templating_Storage_TestStorage extends Symfony_Component_Templating_Storage_Storage
{
    public function getContent()
    {
    }
}

?>
