no: snow0
land:
    name: 滴凍山ふもと
    name0: FrostyMountain(foot)
    land: snow
    proper: 'Lv??'
monster:
    1036:
        - 100
        - 1
    1037:
        - 100
        - 1
    1038:
        - 100
        - 1
    1039:
        - 100
        - 1
trigger:
    item:
        -
            8009: 1
subs:
    land:
        snow1:
            no: snow1
            land:
                name: 滴凍山(中腹)
                name0: FrostyMountain(HalfWay)
                land: snow
                proper: 'Lv??'
            monster:
                1040:
                    - 100
                    - 1
                1041:
                    - 100
                    - 1
                1042:
                    - 100
                    - 1
                1043:
                    - 100
                    - 1
                1044:
                    - 40
                    - 1
                1045:
                    - 15
                    - 0
                1046:
                    - 10
                    - 0
            trigger:
                item:
                    - { 8010: 1 }
        snow2:
            no: snow2
            land:
                name: 滴凍山(頂上)
                name0: FrostyMountain(Top)
                land: snow
                proper: 'Lv??'
            monster:
                1089:
                    - 80
                    - 1
                1090:
                    - 80
                    - 1
                1044:
                    - 30
                    - 1
                1047:
                    - 100
                    - 1
                1048:
                    - 60
                    - 1
                1049:
                    - 5
                    - 0
                1046:
                    - 10
                    - 0
            trigger:
                item:
                    - { 8011: 1 }
