no: ac0
land:
    name: 古の洞窟
    name0: TheAncientCave
    land: cave
    proper: 'Lv??'
monster:
    1010:
        - 0
        - 1
    1011:
        - 0
        - 1
    1012:
        - 500
        - 0
    1013:
        - 150
        - 1
    1014:
        - 150
        - 1
    1015:
        - 150
        - 1
    1016:
        - 100
        - 0
    1017:
        - 50
        - 0
trigger:
    item:
        -
            8000: 1
