no: snow2
land:
    name: 滴凍山(頂上)
    name0: FrostyMountain(Top)
    land: snow
    proper: 'Lv??'
monster:
    1089:
        - 80
        - 1
    1090:
        - 80
        - 1
    1044:
        - 30
        - 1
    1047:
        - 100
        - 1
    1048:
        - 60
        - 1
    1049:
        - 5
        - 0
    1046:
        - 10
        - 0
trigger:
    item:
        -
            8011: 1
