extension_dir = "D:\Users\WebstormProjects\php\bin\php-5.6.32-nts-Win32-VC11-x64\ext"
extension = php_mbstring.dll
date.timezone = "Asia/Taipei"

include_path = "D:\Users\WebstormProjects\game\Hall-of-Fame\.codenomad\worktrees\develop5\hof\includes;."
